# File: .github/workflows/ci.yml
name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start the application
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Test synonym endpoint
        run: |
          response=$(curl -X 'POST' \
            'http://127.0.0.1:8000/synonyms' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '{"word": "happy"}')

          echo "Response: $response"

          expected_response='{\
            "input_word": "happy",\
            "synonyms": [\
              {"word": "Joyful", "similarity_score": 0.5850727882362465},\
              {"word": "Glad", "similarity_score": 0.5614796465770227},\
              {"word": "Cheerful", "similarity_score": 0.5558027769025328},\
              {"word": "Delighted", "similarity_score": 0.5462781052460954},\
              {"word": "Pleased", "similarity_score": 0.5436315751143872},\
              {"word": "Elated", "similarity_score": 0.5330383935437045},\
              {"word": "Ecstatic", "similarity_score": 0.5243368697389907},\
              {"word": "Jovial", "similarity_score": 0.47522304082557587},\
              {"word": "Merry", "similarity_score": 0.4476358721685514},\
              {"word": "Content", "similarity_score": 0.3661071399499329}\
            ]\
          }'

          if [ "$response" != "$expected_response" ]; then
            echo "Test failed."
            exit 1
          else
            echo "Test passed."
          fi
